### ISSUE TITLE
[Buchla] Clock div app expects bipolar CV for div/mult, doesn’t work for Buchla CV

### ISSUE THREAD

**Issue by mathomas** [Chysn/O_C-HemisphereSuite#31]
The clock divider/multiplier app accepts bipolar CV to adjust division/multiplication.  In the Buchla world, all CV is unipolar.  Thus it is impossible to reach the multiplication side of the app via CV (for, say, ratcheting).

In a Buchla unipolar, 0-10v CV, world, it might make sense to have 0-4.99v represent multiplication and 5-10v represent division (essentially offsetting the input expectations).

This is probably an issue in multiple apps, so if the expectation change can be generic that would be a win.

**Comment by Chysn** [comment]
Good call, thanks. I'm working on this now. Since the non-Buchla O_C has a non-symmetrical range (-3V to 5V), the CV range is -2.5V to 0V for multiplication and 0V to 2.5V for division. So for Buchla, the operative range will probably wind up being 2.5V to 5V and 5V to 7.5V. There will be a plus-or-minus-.4V detent centered around 5V to allow for manual (non CV) settings.

**Comment by mathomas** [comment]
Sweet!  I assume it will clip at 7.5v if given more.  Not a problem, just want to test my guess.  The newer 2OC 1.5 appears to have attenuators on the CV ins, so that will be all the better.

**Comment by Chysn** [comment]
Beyond 7.5V, it'll just max out the clock division value at 8.

**Comment by Chysn** [comment]
Closing issue, as no further Buchla work is planned.
