### ISSUE TITLE
Compiling: Blank screen for all versions >= 1.6

### ISSUE THREAD

**Issue by mcleinn** [Chysn/O_C-HemisphereSuite#79]
Dear community, 

I have been using Hemisphere Suite for quite a while: all releases, including 1.8A, install normally via HEX file and boot up.

Now I wanted to build the suite by myself. Unfortunately, I was getting a blank screen after reboot for all latest releases. I went back in history - all releases up to 1.5A compile and run normally (the latest O_C release without hemisphere compiles and runs, as well). But all releases beginning from 1.6 result in a blank screen.

I then narrowed it down to the breaking commit.
Until "Add VectMorph" 27.10.2018 it still works
Starting from "Add 32rd Waveform Library entry" 27.10.2018 it does not work.

There were no significant changes in this commit, so I suspected the code would have grown too big, even though there had been no error message. I changed optimization from "Faster" to "Smallest code" - and everything started to work, even with the 1.8A release.

Maybe I missed something in the Hemisphere build instructions, but they seem to say one should use the same settings as O_C, besides "USB type: Midi" - the O_C manual advises to set optimization to "Faster", which does not work with newer versions of Hemisphere, at least with my Teensyduino configuration.

Greetings

**Comment by mz2250** [comment]
Hi, you really have to use both Arduino ide and teensyduino version suggested in Ornament firmware upload procedure manual.

"method B: compiling the firmware
step 1): get the IDE + teensyduino add-on
if you don’t have it already, you need to install the Arduino IDE as well as the Teensyduino v1.35 add-on. Note that you MUST use specific versions of these! At the time of writing, that’s Arduino IDE 1.8.1 (available from https://www.arduino.cc/en/Main/OldSoftwareReleases - just scroll down and it’s in the table) and Teensyduino v1.35 ([Mac] [Windows] [Linux]), respectively; at this point, later versions of Teensyduino (which use gcc 5.4 instead of gcc 4.8) do not work, so please don’t use them (they will cause screen corruptions). Only use Teensyduino v1.35!"

You can download the teensyduino here

https://ornament-and-cri.me/firmware/

**Comment by Chysn** [comment]
This is more of a support issue than a bug report, so it doesn't really belong here. I'm going to close the issue. Build with the versions specified in the documentation, and all will be fine.

**Comment by mcleinn** [comment]
I saw that, but it is quite impractical to ask people who are doing all
kinds of modern Teensy and Arduino development to install IDE and libraries
which are several years old. In fact, compilation does work with modern
libraries, just with the small code optimization, which is largely
identical to - o2.

mz2250 <notifications@github.com> schrieb am Mi., 6. Jan. 2021, 04:48:

**Comment by mz2250** [comment]
That was already discussed a lot, I saw it's something related to the first version of ornament and can't be changed, you can always have on your machine both the teensyduino 2 and 1.35 and both the newer arduino ide and 1.8.1, just rename the app to something like arduino_2 and it will work

**Comment by mcleinn** [comment]
I see. But, as I wrote, it is actually compiling and running with the
latest version of IDE and libraries, I just needed to switch on "small
code" optimization. So I wonder if this rule, which could turn away people,
is still necessary. Are there any tests you can recommend to see if it
works at the regular frequency?

mz2250 <notifications@github.com> schrieb am Mi., 6. Jan. 2021, 14:17:

**Comment by mz2250** [comment]
Here's a response from chysn itself on lines forum to same request.

https://llllllll.co/t/hemisphere-suite-support/21704/33

I think it's a better investigation asking in original o_C firmware git from mxmxmx since hemisphere it's an alternative Firmware.

But I'm not speaking on behalf of chysn, so maybe he can add more on that.
