### ISSUE TITLE
Trigger Sequncer

### ISSUE THREAD

**Issue by sjfernandez** [Chysn/O_C-HemisphereSuite#85]
Hi

Wasn't sure if this was the right place but I use the trigger sequencer to trigger envelopes and other things that expect gates, as you know triggers are too short for such a task but I was wondering if it was possible to add an option to set the trigger length maybe via holding the button to get to an option screen

Thanks

**Comment by Chysn** [comment]
The default trigger length of 6ms should be sufficient for any Eurorack trigger input. Modules typically look for a leading edge rather than for a specific time, so if your modules aren't being triggered, there might be a hardware problem with your O_C module.

If you do need to adjust the time, this is done in software/o_c_REV/HemisphereApplet.h, where HEMISPHERE_CLOCK_TICKS is defined. There are 16.66 clock ticks per ms, so just multiply 16.66 x desired ms, and round to an integer.

I have no plans to add a trigger length adjustment to the interface, because there haven't been any real-world cases where the default trigger length is insufficient. It sounds like you might be trying to use triggers as gates, and Eurorack offers plenty of ways to address that kind of thing.
